### ISSUE TITLE
keeps on showing modern twitter

### ISSUE THREAD

**Issue by fukionline** [dimdenGD/OldTwitter#856]
**Describe the bug**
TypeError: Cannot read properties of null (reading 'append') at appendTweet (chrome-extension://phceidoclcdafndndnhepaikidnobjio/scripts/helpers.js:3660:31) at async updateReplies (chrome-extension://phceidoclcdafndndnhepaikidnobjio/layouts/tweet/script.js:184:29) at async chrome-extension://phceidoclcdafndndnhepaikidnobjio/layouts/tweet/script.js:894:13 at 1805291073758965870 (OldTwitter v1.8.5.1)

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/55027860/9cb82683-f526-453b-85a6-984899af11c8)

**Browser**
Microsoft edge

**Links**
Everywhere

**OldTwitter version**
v1.8.5.1

**Comment by PukaCyi** [comment]
+1 this
--
it's also occurring for me

error: TypeError: Cannot read properties of null (reading 'append') at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:3660:31) at async updateReplies (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/tweet/script.js:184:29) at async chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/tweet/script.js:894:13 at 1806561440393818158 (OldTwitter v1.8.5.1)

console: TypeError: Cannot read properties of null (reading 'append')
    at appendTweet (helpers.js:3660:31)
    at async updateReplies (script.js:184:29)
    at async script.js:894:13
appendTweet @ helpers.js:3665

helpers.js:3665  TypeError: Cannot read properties of null (reading 'append')
    at appendTweet (helpers.js:3660:31)
    at async updateReplies (script.js:200:17)
    at async script.js:894:13
appendTweet @ helpers.js:3665

script.js:447  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'append')
    at appendComposeComponent (script.js:447:15)
    at updateReplies (script.js:190:60)
    at async script.js:894:13
        
helpers.js:1255  Uncaught (in promise) TypeError: Cannot set properties of null (setting 'innerHTML')
    at renderTrends (helpers.js:1255:31)
