### ISSUE TITLE
“TypeError”, Windows 11, OldTwitter v1.8.9

### ISSUE THREAD

**Issue by HappyHappy01** [dimdenGD/OldTwitter#938]
This message came up when I was reading my Twitter feed:
TypeError: Cannot read properties of undefined (reading 'length') at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1931:94) at renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/home/script.js:329:37) at 1835731735910264836 (OldTwitter v1.8.9)
Please advise.

Bob

**Comment by yorunoken** [comment]
when did this happen / what were you doing when this happened?
